-- Local Data Export Dump
-- Generated: 2026-09-09 07:03:33

-- Table: users
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('1', 'Administrator', 'adminelcoding', 'admin@elcoding.id', 'user', NULL, '$2y$12$ExqZwfKoQmOcIVdmQZ25ju22esGsOz14RmxRn63v9M0alIdl/0ov.', NULL, '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('2', 'Siswa Magang ELC', NULL, 'siswa.pkl@elc.my.id', 'pkl_student', NULL, '$2y$12$3Eo90gfnuvP6fBidIY9n.e/D94e0Pkh8Eiz7DLi2RAvvgf8nb0Qy.', NULL, '2026-09-09 04:16:09', '2026-09-09 04:16:09');

-- Table: layanans
INSERT INTO `layanans` (`id`, `title`, `slug`, `icon`, `badge`, `short_description`, `price_label`, `price`, `price_amount`, `price_period`, `image_path`, `description`, `features_main`, `pricing_includes`, `features_full`, `whatsapp_message`, `created_at`, `updated_at`) VALUES ('1', 'Jasa Pembuatan Website & Web Application', 'pembuatan-website-aplikasi-web', 'fas fa-globe', 'RECOMMENDED', 'Pengembangan website responsif, company profile, toko online (e-commerce), dan sistem informasi bisnis berbasis Laravel & React.', 'Mulai Dari', 'Rp 2.500.000', '2500000', '/ project', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80', 'Kami menyediakan jasa pembuatan website profesional yang dirancang khusus untuk meningkatkan kredibilitas dan penjualan bisnis Anda. Menggunakan teknologi modern terkini dengan desain elegan, SEO-friendly, dan akses super cepat.', '[\"Desain Responsive & Modern\",\"Optimasi SEO & Kecepatan Tinggi\",\"Integrasi Payment Gateway\",\"Gratis Domain & Hosting 1 Tahun\"]', '[\"Free Source Code\",\"Gratis Revisi Desain\",\"Garansi & Support 6 Bulan\",\"Panduan Penggunaan Admin Panel\"]', '[\"Desain Kustom Eksklusif (Non-Template)\",\"Content Management System (CMS) Mudah Digunakan\",\"Integrasi WhatsApp & Live Chat Widget\",\"Keamanan SSL Certificate Terpasang\",\"Analitik Pengunjung (Google Analytics)\"]', 'Halo Elcoding, saya ingin berkonsultasi mengenai Jasa Pembuatan Website & Web Application.', '2026-09-07 03:00:06', '2026-09-07 03:00:06');
INSERT INTO `layanans` (`id`, `title`, `slug`, `icon`, `badge`, `short_description`, `price_label`, `price`, `price_amount`, `price_period`, `image_path`, `description`, `features_main`, `pricing_includes`, `features_full`, `whatsapp_message`, `created_at`, `updated_at`) VALUES ('2', 'Pengembangan Aplikasi Mobile (Android & iOS)', 'pengembangan-aplikasi-mobile', 'fas fa-mobile-alt', 'TERLARIS', 'Aplikasi mobile cross-platform performa tinggi menggunakan Flutter & React Native dengan desain UI/UX interaktif.', 'Mulai Dari', 'Rp 4.500.000', '4500000', '/ project', 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&q=80', 'Wujudkan ide aplikasi mobile impian Anda untuk Android dan iOS dalam satu codebase efisien. Dilengkapi backend API terstruktur, push notification, serta performa native yang mulus.', '[\"Support Android & iOS\",\"UI\\/UX Interactive & Smooth\",\"Push Notification Realtime\",\"Integrasi API & Cloud DB\"]', '[\"Bantuan Publish ke Google PlayStore & AppStore\",\"Dokumentasi REST API Complete\",\"Free Maintenance 3 Bulan\"]', '[\"Multi-language Support\",\"Fitur Lokasi \\/ GPS Mapping\",\"Sistem Keamanan Auth JWT & Biometric Login\",\"Optimasi Ukuran App & Baterai\"]', 'Halo Elcoding, saya berminat membuat Aplikasi Mobile untuk bisnis saya.', '2026-09-07 03:00:06', '2026-09-07 03:00:06');
INSERT INTO `layanans` (`id`, `title`, `slug`, `icon`, `badge`, `short_description`, `price_label`, `price`, `price_amount`, `price_period`, `image_path`, `description`, `features_main`, `pricing_includes`, `features_full`, `whatsapp_message`, `created_at`, `updated_at`) VALUES ('3', 'Jasa UI/UX Design & Prototyping', 'jasa-ui-ux-design-prototyping', 'fas fa-paint-brush', 'PROMO', 'Perancangan antarmuka pengguna (UI) dan pengalaman pengguna (UX) berbasis penelitian pengguna dan Design System scalable.', 'Mulai Dari', 'Rp 1.200.000', '1200000', '/ project', 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&w=800&q=80', 'Layanan pembuatan kraf wireframe, prototype interaktif Figma, serta Design System standar industri untuk mempermudah proses koding tim developer Anda.', '[\"Figma Source File (.fig)\",\"Design System & Component Library\",\"Clickable Interactive Prototype\",\"User Research & Wireframing\"]', '[\"Export Aset SVG\\/PNG\\/JPG\",\"Design Handoff ke Developer\",\"Revisi Sesuai Feedback\"]', '[\"UX Audit & Usability Testing\",\"Responsive Layouts (Desktop & Mobile)\",\"Iconography & Design Palette Custom\"]', 'Halo Elcoding, saya butuh layanan Jasa UI/UX Design untuk aplikasi saya.', '2026-09-07 03:00:06', '2026-09-07 03:00:06');
INSERT INTO `layanans` (`id`, `title`, `slug`, `icon`, `badge`, `short_description`, `price_label`, `price`, `price_amount`, `price_period`, `image_path`, `description`, `features_main`, `pricing_includes`, `features_full`, `whatsapp_message`, `created_at`, `updated_at`) VALUES ('4', 'Private Corporate IT Training', 'private-corporate-it-training', 'fas fa-users-cog', 'SPECIAL', 'Pelatihan teknologi dan pemrograman khusus perusahaan & instansi dengan kurikulum kustom disesuaikan kebutuhan industri Anda.', 'Mulai Dari', 'Rp 3.500.000', '3500000', '/ batch', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80', 'Tingkatkan kompetensi digital tim internal perusahaan Anda dalam topik Fullstack Web Development, DevOps, Cloud Infrastructure, atau AI/Data Science bersama instruktur praktisi berpengalaman.', '[\"Kurikulum Custom Sesuai Project Tim\",\"Instruktur Expert Praktisi Industri\",\"Modul & Sertifikat Pelatihan\",\"Konsultasi Studi Kasus Real\"]', '[\"Materi Presentasi & Source Code\",\"Sertifikat Kelulusan Peserta\",\"Evaluasi Hasil Pembelajaran\"]', '[\"Pilihan Metode Onsite atau Online Live Class\",\"Recording Sesi Pelatihan Harian\",\"Group Support Telegram \\/ Slack Dedikasi\"]', 'Halo Elcoding, kami ingin mengadakan Corporate IT Training untuk perusahaan kami.', '2026-09-07 03:00:06', '2026-09-07 03:00:06');
INSERT INTO `layanans` (`id`, `title`, `slug`, `icon`, `badge`, `short_description`, `price_label`, `price`, `price_amount`, `price_period`, `image_path`, `description`, `features_main`, `pricing_includes`, `features_full`, `whatsapp_message`, `created_at`, `updated_at`) VALUES ('5', 'Cloud Server, DevOps & Maintenance', 'cloud-devops-maintenance-server', 'fas fa-server', 'POPULER', 'Konfigurasi cloud server (AWS, GCP, VPS), automasi CI/CD pipeline, monitoring keamanan, dan perawatan server berkala.', 'Mulai Dari', 'Rp 990.000', '990000', '/ bulan', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80', 'Jaga kestabilan dan keamanan aplikasi bisnis Anda tanpa perlu khawatir server down. Layanan DevOps dan managed server profesional untuk skalabilitas bisnis tinggi.', '[\"Setup Cloud VPS \\/ Server AWS GCP\",\"Automasi Deployment CI\\/CD\",\"Backup Database Otomatis Harian\",\"Monitoring Server 24\\/7 Uptime\"]', '[\"Firewall & Hardening Security\",\"SSL Certificate Management\",\"Laporan Performa Bulanan\"]', '[\"Docker & Kubernetes Containerization\",\"Load Balancer Configuration\",\"Penanganan Insiden Darurat (SLA Fast Response)\"]', 'Halo Elcoding, saya butuh layanan Cloud Server & DevOps Maintenance.', '2026-09-07 03:00:06', '2026-09-07 03:00:06');
INSERT INTO `layanans` (`id`, `title`, `slug`, `icon`, `badge`, `short_description`, `price_label`, `price`, `price_amount`, `price_period`, `image_path`, `description`, `features_main`, `pricing_includes`, `features_full`, `whatsapp_message`, `created_at`, `updated_at`) VALUES ('6', 'Audit Keamanan Website & PenTest', 'audit-keamanan-website-penetration-testing', 'fas fa-shield-alt', 'BARU', 'Pengujian penetrasi (Penetration Testing) dan analisis celah keamanan website serta server aplikasi dari potensi peretasan.', 'Mulai Dari', 'Rp 1.950.000', '1950000', '/ audit', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80', 'Lindungi data sensitif pelanggan dan reputasi bisnis Anda dari ancaman cyber crime, SQL injection, XSS, dan kebocoran data dengan pengujian keamanan standar OWASP.', '[\"Vulnerability Assessment OWASP Top 10\",\"Penetration Testing Blackbox & Graybox\",\"Laporan Rekomendasi Perbaikan\",\"Re-Testing Setelah Fix Celah\"]', '[\"Dokumen Executive Summary Audit\",\"Panduan Remediasi Teknis\",\"Sertifikat Audit Keamanan\"]', '[\"Pemeriksaan Security Header & Network Port\",\"Analisis Kerentanan API Endpoint\",\"Konsultasi Tim Security Specialist\"]', 'Halo Elcoding, saya ingin berkonsultasi untuk Audit Keamanan Website / PenTest.', '2026-09-07 03:00:06', '2026-09-07 03:00:06');

-- Table: program_kursuses
INSERT INTO `program_kursuses` (`id`, `title`, `duration`, `price`, `price_amount`, `badge`, `description`, `created_at`, `updated_at`, `image_path`, `features`, `theme_color`) VALUES ('1', 'Bootcamp Intensif Full Stack Web Dev', '4 Bulan', 'Rp2.500.000', NULL, 'Recommended', NULL, '2026-08-19 04:27:18', '2026-09-07 02:44:58', 'gambar/aset/bootcamp-fullstack.png', NULL, 'theme-1');
INSERT INTO `program_kursuses` (`id`, `title`, `duration`, `price`, `price_amount`, `badge`, `description`, `created_at`, `updated_at`, `image_path`, `features`, `theme_color`) VALUES ('2', 'Mastering Skill UI/UX Design', '3 Bulan', 'Rp1.800.000', NULL, 'Terlaris', NULL, '2026-08-19 04:27:18', '2026-09-07 02:50:12', 'gambar/aset/uiux-design.jpg', NULL, 'theme-1');
INSERT INTO `program_kursuses` (`id`, `title`, `duration`, `price`, `price_amount`, `badge`, `description`, `created_at`, `updated_at`, `image_path`, `features`, `theme_color`) VALUES ('3', 'Professional Class Digital Marketing', '2 Bulan', 'Rp1.500.000', NULL, 'Reguler', NULL, '2026-08-19 04:27:18', '2026-09-07 02:55:39', 'gambar/aset/digital-marketing.jpg', NULL, 'theme-1');

-- Table: pkl_profiles
INSERT INTO `pkl_profiles` (`id`, `user_id`, `institution`, `major`, `student_id_number`, `phone_number`, `address`, `start_date`, `end_date`, `status`, `program_id`, `mentor_id`, `created_at`, `updated_at`) VALUES ('1', '2', 'SMK Negeri 1 Semarang', 'Rekayasa Perangkat Lunak', '2026998811', '081234567890', 'Jl. Pemuda No. 123, Semarang', '2026-09-01', '2026-12-09', 'active', '1', NULL, '2026-09-09 04:16:10', '2026-09-09 04:16:10');

-- Table: pkl_tasks
INSERT INTO `pkl_tasks` (`id`, `pkl_profile_id`, `assigned_by`, `title`, `description`, `due_date`, `status`, `submission_url`, `submission_file`, `submission_notes`, `submitted_at`, `grade`, `feedback`, `created_at`, `updated_at`) VALUES ('1', '1', '1', 'Membuat ERD & Skema Database Sistem PKL', 'Rancanglah diagram ERD dan struktur relasi antartabel untuk portal magang.', '2026-09-16', 'pending', NULL, NULL, NULL, NULL, NULL, NULL, '2026-09-09 04:16:10', '2026-09-09 04:16:10');

-- Table: pkl_histories
INSERT INTO `pkl_histories` (`id`, `pkl_profile_id`, `activity_type`, `title`, `description`, `icon`, `logged_at`, `created_at`, `updated_at`) VALUES ('1', '1', 'registration', 'Pendaftaran Akun PKL Berhasil', 'Mendaftar sebagai peserta PKL dari SMK Negeri 1 Semarang (Rekayasa Perangkat Lunak).', 'fa-user-check', '2026-09-09 04:16:10', '2026-09-09 04:16:10', '2026-09-09 04:16:10');

-- Table: mitras
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('1', 'Partner Logo 1 (1)', 'gambar/mitra/Partner_Logo_1__1_.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('2', 'Partner Logo 1 (2)', 'gambar/mitra/Partner_Logo_1__2_.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('3', 'Partner Logo 1', 'gambar/mitra/Partner_Logo_1.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('4', 'Partner Logo 2 (1)', 'gambar/mitra/Partner_Logo_2__1_.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('5', 'Partner Logo 2', 'gambar/mitra/Partner_Logo_2.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('6', 'Partner Logo 3 (1)', 'gambar/mitra/Partner_Logo_3__1_.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('7', 'Partner Logo 3', 'gambar/mitra/Partner_Logo_3.png', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('8', 'Partner Logo 3', 'gambar/mitra/Partner_Logo_3.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('9', 'Partner Logo 4 (1)', 'gambar/mitra/Partner_Logo_4__1_.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('10', 'Partner Logo 4 (2)', 'gambar/mitra/Partner_Logo_4__2_.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('11', 'Partner Logo 4', 'gambar/mitra/Partner_Logo_4.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('12', 'Partner Logo 5 (1)', 'gambar/mitra/Partner_Logo_5__1_.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `mitras` (`id`, `name`, `logo_path`, `created_at`, `updated_at`) VALUES ('13', 'Partner Logo 5', 'gambar/mitra/Partner_Logo_5.svg', '2026-08-19 04:27:18', '2026-08-19 04:27:18');

-- Table: portofolios
INSERT INTO `portofolios` (`id`, `title`, `category`, `image_path`, `created_at`, `updated_at`, `content`, `client`, `date`) VALUES ('1', 'Film Islami Kemenag', 'Coding', 'gambar/portofolio/Film-Islami-Kemenag.webp', '2026-08-19 04:27:18', '2026-08-19 04:27:18', 'Proyek pembuatan website untuk Kemenag dengan fitur streaming film islami.', NULL, NULL);
INSERT INTO `portofolios` (`id`, `title`, `category`, `image_path`, `created_at`, `updated_at`, `content`, `client`, `date`) VALUES ('2', 'TOSTEM Prima Cipta', 'Desain Grafis', 'gambar/portofolio/Tostem-Prima-Cipta.webp', '2026-08-19 04:27:18', '2026-08-19 04:27:18', 'Pembuatan desain profil perusahaan dan materi promosi untuk TOSTEM Prima Cipta.', NULL, NULL);
INSERT INTO `portofolios` (`id`, `title`, `category`, `image_path`, `created_at`, `updated_at`, `content`, `client`, `date`) VALUES ('3', 'Tutur Bangsa', 'B. Inggris & Mandarin', 'gambar/portofolio/Tutur-Bangsa.webp', '2026-08-19 04:27:18', '2026-08-19 04:27:18', 'Sistem e-learning interaktif untuk pembelajaran bahasa.', NULL, NULL);
INSERT INTO `portofolios` (`id`, `title`, `category`, `image_path`, `created_at`, `updated_at`, `content`, `client`, `date`) VALUES ('4', 'Kerjasama Pengembangan Sinergis dengan LazizMU', 'Kerjasama', 'gambar/portofolio/kerjasama-lazizmu.webp', '2026-09-02 04:52:44', '2026-09-02 04:52:44', 'Elcoding Academy menjalin kerjasama strategis dengan LazizMU dalam rangka pengembangan sistem digital sinergis, optimalisasi tata kelola teknologi informasi, dan peningkatan efisiensi layanan secara terpadu.', 'LazizMU', '2026-09-02');

-- Table: artikels
INSERT INTO `artikels` (`id`, `title`, `author`, `category`, `status`, `published_at`, `created_at`, `updated_at`, `content`, `image_path`) VALUES ('1', 'Mengapa Belajar Pemrograman Adalah Investasi Terbaik untuk Masa Depan Anda', 'Admin Elcoding', 'Teknologi', 'Published', '2026-06-24', '2026-08-19 04:27:18', '2026-08-19 04:27:18', 'Di era digital yang berkembang dengan sangat pesat, kemampuan pemrograman atau coding telah berubah dari sekadar keahlian teknis khusus menjadi salah satu keterampilan dasar yang paling dicari oleh berbagai industri di seluruh dunia.

Banyak orang mengira bahwa coding hanya diperuntukkan bagi mereka yang ingin menjadi software engineer atau IT support. Faktanya, pemahaman dasar tentang cara kerja perangkat lunak dan logika pemrograman dapat memberikan keuntungan kompetitif yang besar di hampir setiap bidang karier.', NULL);
INSERT INTO `artikels` (`id`, `title`, `author`, `category`, `status`, `published_at`, `created_at`, `updated_at`, `content`, `image_path`) VALUES ('2', '5 Tips Memilih Bootcamp Web Developer yang Tepat', 'Admin Elcoding', 'Edukasi', 'Published', '2026-06-20', '2026-08-19 04:27:18', '2026-08-19 04:27:18', 'Memilih bootcamp yang tepat adalah langkah penting. Pastikan Anda mempertimbangkan:
1. Kurikulum yang up to date
2. Mentor yang berpengalaman
3. Fokus pada praktik (project-based)
4. Dukungan penyaluran kerja
5. Fasilitas yang memadai', NULL);
INSERT INTO `artikels` (`id`, `title`, `author`, `category`, `status`, `published_at`, `created_at`, `updated_at`, `content`, `image_path`) VALUES ('3', 'Mengenal Perbedaan UI dan UX Design untuk Pemula', 'Tim Kreatif', 'Desain', 'Draft', '2026-06-18', '2026-08-19 04:27:18', '2026-08-19 04:27:18', 'User Interface (UI) dan User Experience (UX) adalah dua hal yang berbeda. UI fokus pada tampilan antarmuka (warna, tombol, tipografi), sedangkan UX berfokus pada kemudahan dan pengalaman pengguna saat menggunakan aplikasi. Keduanya harus berjalan beriringan untuk menciptakan produk digital yang sukses.', NULL);
INSERT INTO `artikels` (`id`, `title`, `author`, `category`, `status`, `published_at`, `created_at`, `updated_at`, `content`, `image_path`) VALUES ('4', 'Kerjasama Pengembangan Sinergis dengan LazizMU', 'Admin Elcoding', 'Kerjasama', 'Published', '2026-09-02', '2026-09-02 05:02:20', '2026-09-02 05:02:19', '<p>Elcoding Academy secara resmi menjalin kerjasama pengembangan sinergis dengan LazizMU. Kerjasama ini bertujuan untuk memperkuat ekosistem digital, mempercepat otomatisasi layanan, serta meningkatkan efisiensi tata kelola teknologi informasi secara berkesinambungan.</p><p>Melalui kolaborasi ini, kedua pihak berkomitmen untuk menghadirkan inovasi solusi perangkat lunak yang andal dan tepat guna untuk mendukung berbagai program operasional LazizMU secara optimal.</p>', 'gambar/artikel/kerjasama-lazizmu.webp');
INSERT INTO `artikels` (`id`, `title`, `author`, `category`, `status`, `published_at`, `created_at`, `updated_at`, `content`, `image_path`) VALUES ('5', 'Training & Pelatihan Website Elrhea', 'Admin Elcoding', 'Edukasi', 'Published', '2026-07-22', '2026-09-02 05:14:36', '2026-09-02 05:14:36', '<p><strong>Elcoding Academy</strong> sukses menyelenggarakan program <em>Training &amp; Pelatihan Website Elrhea</em> yang berlangsung pada tanggal 21 hingga 22 Juli 2026 di Semarang.</p><p>Kegiatan pelatihan ini dirancang untuk memberikan pemahaman mendalam serta keterampilan praktis dalam pengolahan, pengelolaan, dan pengoperasian website secara mandiri dan profesional. Peserta dibimbing langsung oleh tim instruktur berpengalaman dari Elcoding Academy.</p><p style=\"text-align: center; margin: 25px 0;\"><img src=\"/gambar/artikel/training-pelatihan-elrhea-2.webp\" alt=\"Dokumentasi Pelatihan Website Elrhea\" style=\"max-width: 100%; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1);\" /></p><p>Selama dua hari penuh, peserta antusias mengikuti rangkaian materi mulai dari pengenalan struktur pengelolaan sistem, manajemen konten, hingga otomatisasi serta pemeliharaan keandalan sistem website. Diharapkan pelatihan ini mampu meningkatkan efisiensi dan kapasitas digital secara berkelanjutan.</p>', 'gambar/artikel/training-pelatihan-elrhea-1.webp');

-- Table: settings
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('1', 'contact_address', 'CitraLand Tegal blok Belleza Plaza Lt.2, Kraton, Kota Tegal, Jawa Tengah (Gedung Training Center)', '2026-08-19 04:27:18', '2026-08-24 02:21:26');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('2', 'contact_phone', '+62 814-7665-2656', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('3', 'contact_whatsapp_chat', '+6281476652656', '2026-08-19 04:27:18', '2026-08-24 02:21:26');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('4', 'contact_email', 'info@elcodingacademy.com', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('5', 'social_facebook', '#', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('6', 'social_instagram', 'https://www.instagram.com/elcoding.id?igsh=c2pndTFlYW5laXk0&utm_source=qr', '2026-08-19 04:27:18', '2026-08-24 02:21:26');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('7', 'social_youtube', '#', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('8', 'contact_map_iframe', 'https://maps.google.com/maps?q=Azzahra%20Computer%20Tegal&t=&z=17&ie=UTF8&iwloc=&output=embed', '2026-08-19 04:27:18', '2026-08-19 04:27:18');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('9', 'contact_address_bekasi', 'Jl. Alternatif Cibubur Ruko Kranggan Blok Rt16/27, Jatisampurna, Kota Bekasi, Jawa Barat', '2026-08-24 02:21:26', '2026-08-24 02:21:26');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('10', 'contact_phone_bekasi', '+62 877-6233-4232', '2026-08-24 02:21:26', '2026-08-24 02:21:26');
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES ('11', 'contact_email_bekasi', 'info@elcodingacademy.com', '2026-08-24 02:21:26', '2026-08-24 02:21:26');

-- Table: mous
INSERT INTO `mous` (`id`, `nomor_surat`, `perihal`, `lampiran`, `nama_file`, `tanggal`, `lokasi`, `nama_customer`, `pengantar_surat_type`, `pengantar_surat`, `ketentuan_type`, `ketentuan`, `grand_total`, `created_by`, `created_at`, `updated_at`) VALUES ('3', '001/SP-ELC/VII/2026', 'Proposal SIMAQ ERP', '1 Berkas Proposal Terpadu', 'tes transaksi', '2026-08-17', 'Cibubur', 'Direksi PT Berkah Aqiqah', 'template', 'Dengan hormat,
Kami dari Elcoding, mengajukan penawaran harga untuk jasa pembuatan aplikasi/website sebagai berikut:', 'template', 'Waktu pengerjaan sesuai dengan kesepakatan
Harga diatas sudah termasuk biaya instalasi dan deployment
Garansi pemeliharaan selama 3 bulan
Pembayaran DP 50% dari total biaya
Pembayaran dapat ditransfer ke Rekening Elcoding', '10000', 'Zaky Afrizal', '2026-08-17 02:15:46', '2026-08-17 03:21:49');
INSERT INTO `mous` (`id`, `nomor_surat`, `perihal`, `lampiran`, `nama_file`, `tanggal`, `lokasi`, `nama_customer`, `pengantar_surat_type`, `pengantar_surat`, `ketentuan_type`, `ketentuan`, `grand_total`, `created_by`, `created_at`, `updated_at`) VALUES ('4', '002/MOU-ELC/IX/2026', 'Kerjasama Pengembangan Sinergis dengan LazizMU', '1 Berkas MoU', 'MoU Kerjasama LazizMU', '2026-09-02', 'Jakarta', 'LazizMU', 'template', 'Dengan hormat,
Kami dari Elcoding Academy mengajukan dokumen MoU dan penawaran kerjasama pengembangan sinergis dengan LazizMU.', 'template', 'Waktu pengerjaan sesuai dengan kesepakatan bersama.
Harga dan biaya sudah termasuk pemeliharaan dan sistem pendukung.', '0', 'Elcoding Academy', '2026-09-02 04:52:44', '2026-09-02 04:52:44');

-- Table: mou_sections
INSERT INTO `mou_sections` (`id`, `mou_id`, `title`, `type`, `content`, `images`, `order`, `created_at`, `updated_at`) VALUES ('1', '4', 'BAGIAN 1: KERJASAMA PENGEMBANGAN SINERGIS DENGAN LAZIZMU', 'block', '[{\"type\":\"text\",\"content\":\"<p><strong>Kerjasama Pengembangan Sinergis dengan LazizMU<\\/strong><\\/p><p>Dokumentasi penandatanganan dan pembahasan kerjasama strategis antara Elcoding Academy dan LazizMU untuk pengembangan ekosistem digital terpadu.<\\/p>\"},{\"type\":\"text\",\"content\":\"<p><img src=\\\"\\/gambar\\/portofolio\\/kerjasama-lazizmu.webp\\\" alt=\\\"Kerjasama Pengembangan Sinergis dengan LazizMU\\\" style=\\\"max-width: 100%; height: auto; border-radius: 8px;\\\" \\/><\\/p>\"}]', NULL, '0', '2026-09-02 04:52:44', '2026-09-02 04:52:44');

